objects/CPQ_Release__c.object
<CustomObject>
    <fields>
        <fullName>Objects_count__c</fullName>
        <label>Objects count</label>
        <summaryForeignKey>CPQ_Release_Item__c.CPQ_Release__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

objects/CPQ_Release_Item__c.object
<CustomObject>
    <fields>
        <fullName>CPQ_Release__c</fullName>
        <label>CPQ Release</label>
        <referenceTo>CPQ_Release__c</referenceTo>
        <relationshipLabel>CPQ Release Items</relationshipLabel>
        <relationshipName>CPQ_Release_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id_API_Field__c</fullName>
        <label>External Id API Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ids__c</fullName>
        <inlineHelpText>comma(,) seperated</inlineHelpText>
        <label>Ids</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DataMigrationOperations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>uniqueId__c</fullName>
        <externalId>true</externalId>
        <label>UniqueId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CPQ Release Item</label>
    <nameField>
        <label>Object API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Release Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPQ_User_Story__c.object
<CustomObject>
    <fields>
        <fullName>CPQ_Release__c</fullName>
        <label>CPQ Release</label>
        <referenceTo>CPQ_Release__c</referenceTo>
        <relationshipLabel>CPQ User Stories</relationshipLabel>
        <relationshipName>CPQ_User_Stories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Objects_count__c</fullName>
        <label>Objects count</label>
        <summaryForeignKey>CPQ_User_Story_Item__c.CPQ_User_Story__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>CPQ User Story</label>
    <nameField>
        <label>CPQ User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CPQ_User_Story_Item__c.object
<CustomObject>
    <fields>
        <fullName>CPQ_Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CPQ Release</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CPQ_Release__c.CPQ_Release__c</field>
                <operation>equals</operation>
                <valueField>CPQ_Release__c.CPQ_Release__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CPQ_Release__c</referenceTo>
        <relationshipLabel>CPQ User Story Items</relationshipLabel>
        <relationshipName>CPQ_User_Story_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPQ_User_Story__c</fullName>
        <label>CPQ User Story</label>
        <referenceTo>CPQ_User_Story__c</referenceTo>
        <relationshipLabel>CPQ User Story Items</relationshipLabel>
        <relationshipName>CPQ_User_Story_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id_field_API_name__c</fullName>
        <label>External Id field API name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ids_to_deploy__c</fullName>
        <label>Ids to deploy</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>DataMigrationOperations</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UniqueId__c</fullName>
        <externalId>true</externalId>
        <label>UniqueId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CPQ User Story Item</label>
    <nameField>
        <label>Object API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ User Story Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/DataMigrationOperations.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Insert</fullName>
    </customValue>
    <customValue>
        <fullName>Update</fullName>
    </customValue>
    <customValue>
        <fullName>Upsert</fullName>
    </customValue>
    <customValue>
        <fullName>Delete</fullName>
    </customValue>
    <masterLabel>DataMigrationOperations</masterLabel>
</GlobalValueSet>

classes/CPQUserStoryItemTriggerHandler.cls
public class CPQUserStoryItemTriggerHandler {
    public static void updateUniqueId(List<CPQ_User_Story_Item__c> CPQUserStoryList){
        for(CPQ_User_Story_Item__c CPQUserStoryItemObj : CPQUserStoryList){ 
           CPQUserStoryItemObj.UniqueId__c = CPQUserStoryItemObj.CPQ_User_Story__c+''+CPQUserStoryItemObj.Sequence__c;
        }
    }
    public static void UpdateCPQReleaseItemObject(List<CPQ_User_Story_Item__c> CPQUserStoryList){
        List<Id> CPQReleaseIds = new List<Id>();
        for(CPQ_User_Story_Item__c CPQUserStoryItemObj : CPQUserStoryList){ 
            CPQReleaseIds.add(CPQUserStoryItemObj.CPQ_Release__c);
        }
        Map<string,CPQ_Release_Item__c> cpqRILObj = new Map<string,CPQ_Release_Item__c>();
        Map<string,decimal> cpqReleaseVSObjectCount = new Map<string,decimal>();
        for(CPQ_Release_Item__c cpqRIObj : [select id,CPQ_Release__c,CPQ_Release__r.Objects_count__c,Name,Operation__c,Sequence__c,uniqueId__c,Ids__c,External_Id_API_Field__c from CPQ_Release_Item__c where CPQ_Release__c IN :CPQReleaseIds]){
            string uniqueId = cpqRIObj.CPQ_Release__c+cpqRIObj.Name+cpqRIObj.Operation__c+cpqRIObj.Sequence__c;
            cpqRILObj.put(uniqueId, cpqRIObj);
            cpqReleaseVSObjectCount.put(cpqRIObj.CPQ_Release__c, cpqRIObj.CPQ_Release__r.Objects_count__c);
        }
        List<CPQ_Release_Item__c> cpqRIList = new List<CPQ_Release_Item__c>();
        
         for(CPQ_User_Story_Item__c CPQUSItemObj : CPQUserStoryList){
             
             string uniqueId = CPQUSItemObj.CPQ_Release__c+CPQUSItemObj.Name+CPQUSItemObj.Operation__c+CPQUSItemObj.Sequence__c;
             Decimal sequence = cpqReleaseVSObjectCount.get(CPQUSItemObj.CPQ_Release__c);
             if(cpqRILObj.containsKey(uniqueId)){
                 CPQ_Release_Item__c cpqRIUPdate = new  CPQ_Release_Item__c();
                 cpqRIUPdate.Ids__c = processIds(cpqRILObj.get(uniqueId).Ids__c, CPQUSItemObj.Ids_to_deploy__c);
                 cpqRIUPdate.UniqueId__c = uniqueId;
                 cpqRIList.add(cpqRIUPdate);
             }else{
               CPQ_Release_Item__c cpqRI = new  CPQ_Release_Item__c();
                 cpqRI.Name = CPQUSItemObj.Name;
                 cpqRI.Operation__c = CPQUSItemObj.Operation__c;
                 cpqRI.Sequence__c = sequence+1;
                 cpqRI.Ids__c = CPQUSItemObj.Ids_to_deploy__c;
                 cpqRI.External_Id_API_Field__c = CPQUSItemObj.External_Id_field_API_name__c;
                 cpqRI.UniqueId__c = uniqueId;
                 cpqRI.CPQ_Release__c = CPQUSItemObj.CPQ_Release__c;
                 cpqRIList.add(cpqRI);
             }
         }
        system.debug('cpqRIList-->'+cpqRIList);
        if(cpqRIList.size()>0){
            database.upsert(cpqRIList,CPQ_Release_Item__c.UniqueId__c, false);
        }
        
    }
    public static string processIds(string releaseIds,string userStoryIds){
        string fullIds = releaseIds+','+userStoryIds;
        Set<String> uniqueList = new Set<String>();
		uniqueList.addAll(fullIds.split(','));
        string combinedIds = string.join(new List<String>(uniqueList), ','); 
        return combinedIds;
    }
}