objects/CPQ_Release__c.object
<CustomObject>
</CustomObject>

objects/CPQ_Release_Item__c.object
<CustomObject>
    <fields>
        <fullName>CPQ_Release__c</fullName>
        <label>CPQ Release</label>
        <referenceTo>CPQ_Release__c</referenceTo>
        <relationshipLabel>CPQ Release Items</relationshipLabel>
        <relationshipName>CPQ_Release_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Deployment_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Deployment Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ids__c</fullName>
        <inlineHelpText>comma(,) seperated</inlineHelpText>
        <label>Ids</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Api_Name__c</fullName>
        <label>Object Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CPQ Release Item</label>
    <nameField>
        <label>Object API Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Release Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Data_Migration_Details__c.object
<CustomObject>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Data Migration Details</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Migration Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeploymentController.cls
public class DeploymentController {
	
    @AuraEnabled(cacheable=true) 
    public static List<DeploymentObject> getReleaseDeploymentDetails(String ReleaseId){
        
        List<DeploymentObject> deploymentObjectList = new List<DeploymentObject>();
        List<Data_Migration_Details__c> dataMigrationMetadataList = [select id,Name,Object_API_Name__c from Data_Migration_Details__c order by 	Sequence__c ASC NULLS LAST];
		
        Map<String,CPQ_Release_Item__c> releaseItemMap = new Map<String,CPQ_Release_Item__c>();
        List<CPQ_Release_Item__c> releaseItems = [select Id,Object_Api_Name__c,Ids__c,Deployment_Status__c from CPQ_Release_Item__c where CPQ_Release__c =: ReleaseId ];
        for(CPQ_Release_Item__c releaseItem: releaseItems){
            releaseItemMap.put(releaseItem.Object_Api_Name__c, releaseItem);
        }
        
        for(Data_Migration_Details__c dmd: dataMigrationMetadataList){
            if(releaseItemMap.get(dmd.Object_API_Name__c) != null){           	
               DeploymentObject dobj = new DeploymentObject();
               dobj.ObjectAPIName = dmd.Object_API_Name__c; 
               dobj.ObjectLabel = dmd.Name;
               dobj.Ids = releaseItemMap.get(dmd.Object_API_Name__c).Ids__c;
               dobj.DeploymentStatus = releaseItemMap.get(dmd.Object_API_Name__c).Deployment_Status__c;
               deploymentObjectList.add(dobj); 
            } 
           
        }
        
        return deploymentObjectList;        
    }
    public class DeploymentObject{
        @AuraEnabled public String ObjectAPIName;
        @AuraEnabled public String ObjectLabel;
        @AuraEnabled public String Ids;
        @AuraEnabled public Boolean DeploymentStatus;
        
    }
}