objects/System__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AWS_ApiGateway_URL__c</fullName>
        <label>AWS ApiGateway URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Async_Timeout_Threshold__c</fullName>
        <description>This time out is mainly used for Async Callout from SF</description>
        <label>Async Timeout Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Override_Timeout_Threshold_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Override Timeout Threshold Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Timeout_Threshold__c</fullName>
        <label>Override Timeout Threshold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timeout_Threshold__c</fullName>
        <defaultValue>19999</defaultValue>
        <label>Timeout Threshold</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>System</label>
</CustomObject>

classes/Callout.cls
global class Callout {
    
	global static string SYSTEM_APIGATEWAY_ENDPOINT = (String)System__c.getOrgDefaults().AWS_ApiGateway_URL__c;
	global static boolean SET_OVERRIDE_TIMEOUT =  (boolean)System__c.getOrgDefaults().Override_Timeout_Threshold_Flag__c;
    global static final integer SYSTEM_OVERRIDE_TIMEOUT_THRESHOLD = (Integer)System__c.getOrgDefaults().Override_Timeout_Threshold__c;
    global static final boolean SYSTEM_OVERRIDE_TIMEOUT_THRESHOLD_FLAG = (boolean)System__c.getOrgDefaults().Override_Timeout_Threshold_Flag__c;
    
    global static integer SYSTEM_TIMEOUT_THRESHOLD {
        get{
            SYSTEM_TIMEOUT_THRESHOLD = (Integer)System__c.getOrgDefaults().Timeout_Threshold__c;
            
            if(SET_OVERRIDE_TIMEOUT && SYSTEM_OVERRIDE_TIMEOUT_THRESHOLD_FLAG){
              SYSTEM_TIMEOUT_THRESHOLD = SYSTEM_OVERRIDE_TIMEOUT_THRESHOLD;
            }
            if(System.isFuture()){    // Separate Callout for Async Calls
              SYSTEM_TIMEOUT_THRESHOLD = (Integer)System__c.getOrgDefaults().Async_Timeout_Threshold__c;
            }
    
            return SYSTEM_TIMEOUT_THRESHOLD;
      }set;}
	
    global static HttpResponse doGet(String url){
        
        Http h = new Http();
        HttpRequest req = new HttpRequest();
        req.setEndpoint(SYSTEM_APIGATEWAY_ENDPOINT + url);

        req.setMethod('GET');
        req.setHeader('Accept', 'application/json');
        system.debug('---system time-out threshold is: '+SYSTEM_TIMEOUT_THRESHOLD);
        req.setTimeout(SYSTEM_TIMEOUT_THRESHOLD);
        
        Long start = Datetime.now().getTime();
        HttpResponse res;
        
        try {
            Logger.calloutStart(req);
            res = h.send(req);
        } catch(Exception e) {
            Logger.calloutSetError(e);
        } finally {
            Logger.calloutEnd(res);
        }
        
        // Send the request, and return a response
        return res;
    }
}